services:
  api:
    container_name: customscape-api-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./app:/app/app
      - ./assets:/app/assets
      - ./models:/app/models
    environment:
      - PYTHONPATH=/app

  worker:
    container_name: customscape-worker-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: sh -c "watchmedo auto-restart --patterns='*.py' --recursive -- python -m app.worker"
    env_file:
      - .env
    depends_on:
      - api
    volumes:
      - ./app:/app/app
      - ./models:/app/models
      - ./assets:/app/assets
      - ~/.aws:/root/.aws:ro
    environment:
      - PYTHONPATH=/app
