services:
  api:
    container_name: customscape-api-prod
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./app:/app/app
      - ./assets:/app/assets
      - ./models:/app/models
    environment:
      - PYTHONPATH=/app
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

  worker:
    container_name: customscape-worker-prod
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "python -m app.worker"
    env_file:
      - .env
    depends_on:
      - api
    volumes:
      - ./app:/app/app
      - ./models:/app/models
      - ./assets:/app/assets
    runtime: nvidia
    environment:
      - PYTHONPATH=/app
      - NVIDIA_VISIBLE_DEVICES=all
      - PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
